# Generated by Django 3.2.4 on 2021-06-07 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210607_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='user_poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.userpoll'),
            preserve_default=False,
        ),
    ]
